site_name: MetaTools
site_url: https://loosolab.pages.gwdg.de/software/metadata-organizer/
site_dir: public

nav:
    - Home: index.md
    - User Guide:
        - File Generation: generate.md
        - File Searching: search.md
    - Data structure: 
        - General structure: structure.md
        - Extend structure:
            - Adding keys: add_keys.md
            - whitelists : add_whitelist
theme: readthedocs
