site_name: MetaTools
site_url: https://loosolab.pages.gwdg.de/software/metadata-organizer/
site_dir: public

nav:
    - Home:
        - User Guide:
            - How to Install: index.md
            - File Generation: generate.md
            - File Searching: search.md
            - Plots: plots.md
        - Data structure: 
            - General structure: structure.md
            - Whitelists: whitelists.md
        - Extend structure:
            - Add values to whitelist: add_whitelist_values.md
            - Add new Whitelist: add_whitelist.md
            - Add keys: add_keys.md
            - Add experimental factor: add_factor.md 
theme: readthedocs
