[build-system]
requires = [
    "setuptools",
    "pip"
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["fred"]

[project]
name = "fred"
version = "0.0.1"
dependencies = [
    "PyYAML>=5.1",
    "pytz~=2022.2.1",
    "python-dateutil~=2.8.2",
    "tabulate~=0.9.0",
    "seaborn~=0.13.2",
    "biopython",
    "plotly",
    "jinja2",
    "gitpython",
    "kaleido",
]

[project.scripts]
fred = "fred.metaTools:main"
