structure: mamplan_keys.yaml
whitelist_repository: https://gitlab.gwdg.de/loosolab/software/metadata_whitelists.git
private_access:
  name: # github: username for access token; gitlab: oauth2 for project access token
  token: # personal (github) or project (gitlab) access token
branch: v1.2.*
whitelist_path: FRED_whitelists
update_whitelists: True
output_path: .
filename: 'mamplan' # example_metadata.yaml
